name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pascalora/ora_app
          stage: main
          yaml: |
            name: ora-app
            app: node@16
            options:
              env:
                - name: DB_HOST
                  value: ora.c7yoak2m8npu.ap-northeast-2.rds.amazonaws.com
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: admin
                - name: DB_PASSWORD
                  value: wqdsdsf123!
                - name: DB_DATABASE
                  value: ora
              ports: "4000"
              install: npm ci
              build: npm run build
              start: npm run start:dev
              buildenv: []
            context:
              git:
                url: git@github.com:poeroff/ORA_APP.git
                ref: main
                path: ora_back
              preset: node