name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pascalora/ora_app
          stage: main
          yaml: >
            name: ora-app-django

            app: python@3.12

            options:
              env:
                - name : NODE_BACKEND_SERVER
                  value : https://port-0-ora-app-m1xq0ou447d4b62a.sel4.cloudtype.app
                - name: DJANGO_SETTINGS_MODULE
                  value: ora_python_back.settings
              ports: 8000
              install: |
                pip install --upgrade pip && pip install -r requirements.txt 
               
              start: python -m uvicorn ora_python_back.asgi:application --host 0.0.0.0 --port 8000
              buildenv: []
            context:
              git:
                url: git@github.com:poeroff/ORA_APP.git
                path : ora_python_back
                
              preset: python-django