name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pascalora/ora_app
          stage: main
          yaml: >
            name: ora-app-django

            app: python@3.9

            options:
              env:
                - name: APIKEY
                  value: ${AI_APiKEY}
              ports: 8000
              install: RUN pip install --upgrade pip && pip install -r requirements.txt
               
              start: python3 manage.py runserver 0:8000
              buildenv: []
            context:
              git:
                url: git@github.com:poeroff/ORA_APP.git
                path : ora_python_back
                ref: main
                
              preset: python-django